version: "3.9"

services:
  dashboard:
    image: openjdk:21-jdk
    container_name: dashboard
    ports:
      - 8080:8080
    volumes:
      - ./dashboartRestaurant/target:/app
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/restaurant
      - DATABASE_USERNAME=wewin
      - DATABASE_PASSWORD=1234
    command: java -jar /app/dashboartRestaurant-0.0.1-SNAPSHOT.jar
    depends_on:
      - db
  audit:
    image: openjdk:21-jdk
    container_name: audit
    ports:
      - 8081:8081
    volumes:
      - ./auditoriaRestaurante/target:/app
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/restaurant
      - DATABASE_USERNAME=wewin
      - DATABASE_PASSWORD=1234
    command: java -jar /app/auditoriaRestaurante-0.0.1-SNAPSHOT.jar
    depends_on:
      - db
  db:
    image: postgres:12
    container_name: db
    environment:
      POSTGRES_USER: wewin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: restaurant
    ports:
      - 5432:5432
